improve debian package

diff --git a/.github/workflows/CI.yaml b/.github/workflows/CI.yaml
--- a/.github/workflows/CI.yaml
+++ b/.github/workflows/CI.yaml
@@ -61,6 +61,15 @@ jobs:
           echo "Directory Structure:"
           ls -R
 
+      - name: Check for Cargo.toml
+        run: |
+          if [ -f "/home/runner/work/pepe/Cargo.toml" ]; then
+            echo "Found Cargo.toml"
+          else
+            echo "Cargo.toml not found"
+            exit 1
+          fi
+
       - name: Package Debian (Ubuntu)
         if: matrix.os == 'ubuntu-latest' && (matrix.target == 'x86_64-unknown-linux-gnu' || matrix.target == 'aarch64-unknown-linux-gnu')
         run: |
@@ -80,7 +89,7 @@ jobs:
           Description: HTTP load generator
            Pepe is a command-line HTTP load generator." > pepe/debian/control
 
-          printf "#!/usr/bin/make -f\n%%:\n\tdh \$@\n\noverride_dh_auto_build:\n\techo 'Building the Rust binary...'\n\tcargo build --manifest-path=\$(CURDIR)/../../Cargo.toml --release\n\tls -l ../../target/release\n\noverride_dh_auto_install:\n\techo 'Installing pepe binary...'\n\tinstall -D ../../target/release/pepe \$(DESTDIR)/usr/bin/pepe\n" > pepe/debian/rules
+          printf "#!/usr/bin/make -f\n%%:\n\tdh \$@\n\noverride_dh_auto_build:\n\techo 'Building the Rust binary...'\n\tcargo build --manifest-path=/home/runner/work/pepe/Cargo.toml --release\n\tls -l /home/runner/work/pepe/target/release\n\noverride_dh_auto_install:\n\techo 'Installing pepe binary...'\n\tinstall -D /home/runner/work/pepe/target/release/pepe \$(DESTDIR)/usr/bin/pepe\n" > pepe/debian/rules
 
           echo "pepe (0.1.0) unstable; urgency=low
             * Initial release
